### PR TITLE
Upgrade libs

### PR DESCRIPTION
**Pull request by wingyplus**
Upgrade command logs:

```
$ mix deps.update --all
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  hackney 1.2.0
  hpack_erl 0.2.3
  idna 1.0.3
  kadabra 0.3.4
  makeup 1.0.5
  makeup_elixir 0.15.1
  makeup_erlang 0.1.1
  nimble_parsec 1.1.0
  ssl_verify_hostname 1.0.6
  x509 0.6.0
Upgraded:
  cowboy 2.7.0 => 2.9.0
  cowboy_telemetry 0.3.0 => 0.4.0 (minor)
  cowlib 2.8.0 => 2.11.0
  earmark_parser 1.4.13 => 1.4.15
  ex_doc 0.25.0 => 0.25.3
  mime 1.5.0 => 2.0.1 (major)
  plug 1.11.0 => 1.12.1
  plug_crypto 1.2.0 => 1.2.2
  ranch 1.7.1 => 1.8.0
  telemetry 0.4.2 => 1.0.0 (major)
* Updating plug (Hex package)
* Updating cowboy (Hex package)
* Updating cowboy_telemetry (Hex package)
* Updating ex_doc (Hex package)
* Updating earmark_parser (Hex package)
* Updating telemetry (Hex package)
* Updating cowlib (Hex package)
* Updating ranch (Hex package)
* Updating mime (Hex package)
* Updating plug_crypto (Hex package)
You have added/upgraded packages you could sponsor, run `mix hex.sponsor` to learn more
```

### CODE REVIEW

**Comment by wingyplus** [comment]
Could it introduce breaking changes on `telemetry` since it's bump a version to 1.0? Maybe we should change `cowboy_telemetry` to `0.3.0 or 0.4.0`?

**Comment by josevalim** [comment]
No, this is fine. Updating the lock does not update users of this dependency. The lock is not part of the package.

**Comment by wingyplus** [comment]
> No, this is fine. Updating the lock does not update users of this dependency. The lock is not part of the package.

Oh, I never know that `mix.lock` doesn't affect the package that publishes on hex.pm. 

I found an issue during upgrade telemetry 1.0 in my company project that `plug_cowboy` cannot use `telemetry` 1.0 because `cowboy_telemetry` 0.3 still strict `telemetry` on 0.4. So if we need to make plug_cowboy support on telemetry 1.0 then we should bump a version of `cowboy_telemetry` on mix.exs also?

**Comment by josevalim** [comment]
We already support more recent cowboy telemetry versions in this repo: https://github.com/elixir-plug/plug_cowboy/blob/master/mix.exs#L38

So there is nothing to be bumped or changed here. Make sure you are on latest Hex and do something like `mix deps.update telemetry cowboy_telemetry ...` and other deps that may depend on telemetry. Also make sure the requirements in _your_ mix.exs support the latest version for those too.

I will close this as it seems we are all good here. :)

**Comment by wingyplus** [comment]
@josevalim Thanks for your explaination. :)

**Pull request closed without merging**
