### PR TITLE
Document telemetry events

### PR DESCRIPTION
**Pull request by binaryseed**
Docs for telemetry events added in #31 and #34 

@josevalim

### CODE REVIEW

**Comment by josevalim** [comment]
Looks great! Let's document the measurements and metadata too. Here is a good template: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/logger.ex

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by binaryseed** [comment]
For the type references, is it possible / desired to refer to the erlang specs inside cowboy? For example the `reason`: https://github.com/ninenines/cowboy/blob/master/src/cowboy_stream.erl#L49

**Comment by josevalim** [comment]
It would be good but you will have to refer to them directly in Cowboy docs.

**Pull request merged**
