### PR TITLE
More detailed message for "Cowboy returned 431" error

### PR DESCRIPTION
**Pull request by narkq**
I believe this change could be useful when figuring out how to fix these errors.

Please take a look 🙏

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @narkq, thanks for the PR! I think we are trying to be too smart here, I would prefer to have a mostly consistent message. Also, the request will be the underlying cowboy request and I am not sure how useful it would be. However, I think including the specific reason is a great idea. Maybe we could have a PR only with that? Thanks!

**Comment by narkq** [comment]
To be honest, I also thought that a very large message (considering the fact that we actually hit some limit) isn't a good idea. But still, underlying cowboy request should include at least the peer, which is way better than nothing at all.
Also, I've been lazy and haven't looked yet if it's possible to handle these errors somewhere along the plug pipeline, so I could eventually guess which clients send me those requests. Could you please tell me, is that possible, or the absence of fully parsed request effectively prevents that?

**Comment by josevalim** [comment]
>  Could you please tell me, is that possible, or the absence of fully parsed request effectively prevents that?

Not possible, unfortunately, for the reasons you mentioned.

>  But still, underlying cowboy request should include at least the peer, which is way better than nothing at all.

So what do you think about including the peer and perhaps the method + path?

**Comment by narkq** [comment]
> So what do you think about including the peer and perhaps the method + path?

I think it would be nice, but I'm not sure, should we try to construct a natural language sentence there, or just print a table like this

    peer: 10.10.0.123:35860
    method: POST
    path: <unable no parse>

**Comment by josevalim** [comment]
A print table is totally fine. The simpler the best. :)

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
