### PR TITLE
Add 1.13 to CI matrix

### PR DESCRIPTION
**Pull request by fastjames**
In order to keep up with newer elixir / OTP versions, add 1.13 to the
test matrix (and a few dependency updates to make the new version pass).

Closes https://github.com/elixir-plug/plug_cowboy/issues/80 .

### CODE REVIEW

**Comment by josevalim** [comment]
It may be that updating some dependencies will make earlier Erlang/OTP versions crash.

**Comment by fastjames** [comment]
> It may be that updating some dependencies will make earlier Erlang/OTP versions crash.

The CI failure supports your hypothesis. :-D I will see if I can find a balance point where all the versions can coexist.

**Comment by josevalim** [comment]
Bumping OTP version on Elixir 1.7 may be enough. 21 or 22.

**Comment by fastjames** [comment]
> Bumping OTP version on Elixir 1.7 may be enough. 21 or 22.

Thanks for the suggestion -- it worked in my local testing, so I pushed a change to the OTP version.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
