### PR TITLE
Extend receive to fix flaky drainer test

### PR DESCRIPTION
**Pull request by binaryseed**
I'm hoping that we can work towards the next release, so I'm seeing if this will clear up the test that's been failing in the last few builds

### CODE REVIEW

**Comment by binaryseed** [comment]
I am guessing the switch over to Github Actions just changed the execution speed of the tests or something

@josevalim

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
That didn't seem to have fixed it. :( It seems the issue happens on 23+ only but I cannot reproduce it locally.

**Comment by binaryseed** [comment]
Dang, I was hoping the green PR build was real... I saw the failure just a single time locally the first time I ran that test, but it never repeated.

**Pull request merged**
