### PR TITLE
add recommended Elixir and Erlang/OTP combinations to CI and migrate it from Travis to GitHub Actions 

### PR DESCRIPTION
**Pull request by adrianomitre**
This pull request migrate the CI from Travis CI to GitHub Actions, as requested by José Valim in [this comment](https://github.com/elixir-plug/plug_cowboy/pull/43#issuecomment-663954739).

In addition, it makes sure all recommended Elixir and Erlang/OTP combinations are run on CI.

Quoting José Valim:
> I would still advise folks to go with:
> * For each Elixir version, add a run with earliest supported Erlang/OTP
> * For the last Elixir version, also test the latest supported Erlang/OTP

Please refer to the original discussion on https://github.com/dashbitco/broadway/pull/188 for the full rationale.

Please refer to [Yet another Elixir and Erlang docker image - Chat / Discussions - Elixir Forum](https://elixirforum.com/t/yet-another-elixir-and-erlang-docker-image/28740) for the rationale behing Elixir images by [Hexpm's Bob](https://github.com/hexpm/bob#docker-images).

### CODE REVIEW

**Comment by adrianomitre** [comment]
@josevalim Evidence below suggests that there are tests which behave non-deterministically on Elixir 1.10.4.

Evidence set 1 (same source code, both Elixir 1.10.4 and Erlang/OTP 21.3.8.17, simply changed the image from Ubuntu to Alpine)
- https://github.com/adrianomitre/plug_cowboy/pull/1/checks?check_run_id=912253798 <- passes (Ubuntu)
- https://github.com/adrianomitre/plug_cowboy/pull/1/checks?check_run_id=912259043 <- 23 failures (Ubuntu)
- https://github.com/adrianomitre/plug_cowboy/pull/1/checks?check_run_id=912268399 <- 22 failures (Alpine)

Evidence set 2 (same source code, both Elixir 1.10.4 and Erlang/OTP 22.3.4.4, simply changed the image from Ubuntu to Alpine):
- https://github.com/adrianomitre/plug_cowboy/pull/1/checks?check_run_id=912259047 <- 1 failure (Ubuntu)
- https://github.com/adrianomitre/plug_cowboy/pull/1/checks?check_run_id=912268439 <- passes (Alpine)

Also, tests are failing on master branch for Elixir 1.10.3 and Erlang/OTP 21.1 on Travis CI as well, as can be seen [here](https://travis-ci.org/github/elixir-plug/plug_cowboy/jobs/711881461).

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
It seems the failures happen when booting the Erlang server but I am unable to reproduce them locally with similar versions. :(

**Comment by adrianomitre** [comment]
@josevalim Isn't there a way to hold the tests until the boot is complete? Some techniques from the top of my head are busy-waiting (`while (!is_ready());`), sleeping for a large enough time, in addition to callbacks (`after_boot :enable_tests`).

**Comment by josevalim** [comment]
If cowboy sup tree returns ok, then it should be running. So it is not a matter of waiting (I think).

**Pull request merged**
